spring:
  application:
    name: taskit

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taskit?useSSL=false
    username: root
    password: taskit123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true