spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taskit?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: taskit
    password: taskit123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  servlet:
    context-path: /taskit

jwt:
  http:
    request:
      header: Authorization
  signing:
    key:
      secret: taskit
  token:
    expiration:
      in:
        seconds: 604800

cross-origin:
  front-end: http://localhost:3000

